# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170410_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='and_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
