# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_and_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='and_date',
        ),
    ]
